#pragma once

#ifndef __QBP_DEFINE_PREFIX_DEFINITIONS_HXX
#define __QBP_DEFINE_PREFIX_DEFINITIONS_HXX


#include <QtGlobal>


#define __QBP_DEFINE_PREFIX_APP_VERSION __QBP_APP_VERSION
#define __QBP_DEFINE_PREFIX_QT_VERSION QT_VERSION_STR


#endif // __QBP_DEFINE_PREFIX_DEFINITIONS_HXX
