#pragma once

#ifndef __QBP_MACRO_PREFIX___DEFINITIONS_HXX
#define __QBP_MACRO_PREFIX___DEFINITIONS_HXX


#include <QtGlobal> // QT_VERSION_STR


#define __QBP_MACRO_PREFIX___APP_NAME             "__QBP_APP_NAME__"
#define __QBP_MACRO_PREFIX___APP_VERSION          "__QBP_APP_VERSION__"
#define __QBP_MACRO_PREFIX___ORG_NAME             "__QBP_ORG_NAME__"
#define __QBP_MACRO_PREFIX___ORG_DOMAIN           "__QBP_ORG_DOMAIN__"
#define __QBP_MACRO_PREFIX___APP_DISPLAY_NAME     "__QBP_APP_DISPLAY_NAME__"
#define __QBP_MACRO_PREFIX___APP_COPYRIGHT        "__QBP_APP_COPYRIGHT__"
#define __QBP_MACRO_PREFIX___APP_DESCRIPTION      "__QBP_APP_DESCRIPTION__"
#define __QBP_MACRO_PREFIX___APP_BUILD_DATE       __DATE__
#define __QBP_MACRO_PREFIX___APP_BUILD_TIME       __TIME__
#define __QBP_MACRO_PREFIX___QT_VERSION           QT_VERSION_STR
#define __QBP_MACRO_PREFIX___BREEZE_ICONS_VERSION "__QBP_BREEZE_ICONS_VERSION__"


#endif // __QBP_MACRO_PREFIX___DEFINITIONS_HXX
